# name of action
name: deploy-container

on:
  push:
    branches:
      # Only look for this branch changes
      - main
    paths:
      # This means it will look for any change in the container
      - 'packages/container/**'

defaults:
  run: 
    # Location where is should run
    working-directory: packages/container

# we can have multiple  jobs
jobs: 
  build:
    # Virtual Machine where it would load
    runs-on: ubuntu-latest

    steps:
      # USe Actions and Install dependencies and build.
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build 

      
